"use client";

import { useEffect, useState } from "react";
import Card from "@/components/Card";
import LoadingSpinner from "@/components/LoadingSpinner";
import Sparkline from "@/lib/Sparkline";
import TempDelta from "@/lib/TempDelta";
import WeatherIcon from "@/components/WeatherIcon";
import SevereWeatherMarker from "@/lib/SevereWeatherMarker";
import { useLocation } from "@/context/LocationContext";
import { fetchOpenMeteoForecast, fetchHistoricalWeather } from "@/lib/openMeteo";
import { getWeatherCodeInfo } from "@/lib/weatherCodes";
import type { OpenMeteoResponse } from "@/lib/types";

export default function ReportsPage() {
  const { location } = useLocation();
  const [meteo, setMeteo] = useState<OpenMeteoResponse | null>(null);
  const [historical, setHistorical] = useState<
    { date: string; max: number; min: number; rain: number; wind: number }[]
  >([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!location) return;
    setLoading(true);
    setError(null);

    const end = new Date();
    const start = new Date();
    start.setDate(end.getDate() - 30);
    const fmt = (d: Date) => d.toISOString().slice(0, 10);

    Promise.all([
      fetchOpenMeteoForecast(location.lat, location.lon),
      fetchHistoricalWeather(location.lat, location.lon, fmt(start), fmt(end)),
    ])
      .then(([meteoRes, histRes]) => {
        setMeteo(meteoRes);
        setHistorical(
          histRes.daily.time.map((date, i) => ({
            date,
            max: histRes.daily.temperature_2m_max[i],
            min: histRes.daily.temperature_2m_min[i],
            rain: histRes.daily.precipitation_sum[i],
            wind: histRes.daily.windspeed_10m_max[i],
          }))
        );
      })
      .catch(() => setError("Could not load report data."))
      .finally(() => setLoading(false));
  }, [location]);

  const downloadCsv = () => {
    if (!meteo) return;
    const rows = [["Date", "High (C)", "Low (C)", "Precipitation (mm)", "UV Index", "Wind (km/h)"]];
    meteo.daily.time.forEach((date, i) => {
      rows.push([
        date,
        meteo.daily.temperature_2m_max[i].toFixed(1),
        meteo.daily.temperature_2m_min[i].toFixed(1),
        meteo.daily.precipitation_sum[i].toFixed(1),
        meteo.daily.uv_index_max[i].toFixed(1),
        meteo.daily.windspeed_10m_max[i].toFixed(1),
      ]);
    });
    const csv = rows.map((r) => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${location?.name ?? "weather"}-7day-forecast.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const downloadPdf = async () => {
    if (!meteo || !location) return;
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text(`Weather Report: ${location.name}`, 14, 18);

    doc.setFontSize(11);
    let y = 30;
    doc.text("7-Day Forecast", 14, y);
    y += 8;
    meteo.daily.time.forEach((date, i) => {
      doc.text(
        `${date}: High ${meteo.daily.temperature_2m_max[i].toFixed(0)}C / Low ${meteo.daily.temperature_2m_min[i].toFixed(
          0
        )}C, Rain ${meteo.daily.precipitation_sum[i].toFixed(0)}mm, UV ${meteo.daily.uv_index_max[i].toFixed(1)}`,
        14,
        y
      );
      y += 7;
    });

    if (historical.length > 0) {
      y += 6;
      doc.text("Weather Statistics (last 30 days)", 14, y);
      y += 8;
      const avgTemp =
        historical.reduce((s, d) => s + (d.max + d.min) / 2, 0) / historical.length;
      const totalRain = historical.reduce((s, d) => s + d.rain, 0);
      const hottest = Math.max(...historical.map((d) => d.max));
      const coldest = Math.min(...historical.map((d) => d.min));
      doc.text(`Average temperature: ${avgTemp.toFixed(1)} C`, 14, y);
      y += 7;
      doc.text(`Total rainfall: ${totalRain.toFixed(0)} mm`, 14, y);
      y += 7;
      doc.text(`Hottest day: ${hottest.toFixed(1)} C  |  Coldest night: ${coldest.toFixed(1)} C`, 14, y);
    }

    doc.setFontSize(8);
    doc.text("Generated by SkyWatch. Forecast data: Open-Meteo.", 14, 285);

    doc.save(`${location.name}-weather-report.pdf`);
  };

  if (!location) {
    return (
      <div className="setup-message">
        Pick a city on the Dashboard page first to generate reports.
      </div>
    );
  }

  if (loading) return <LoadingSpinner label="Building your report..." />;
  if (error) return <div className="error-message">{error}</div>;
  if (!meteo) return null;

  const weekHigh = Math.max(...meteo.daily.temperature_2m_max);
  const weekLow = Math.min(...meteo.daily.temperature_2m_min);
  const weekRain = meteo.daily.precipitation_sum.reduce((a, b) => a + b, 0);

  const monthAvg = historical.length
    ? historical.reduce((s, d) => s + (d.max + d.min) / 2, 0) / historical.length
    : null;
  const monthRain = historical.length ? historical.reduce((s, d) => s + d.rain, 0) : null;

  return (
    <div>
      <h1 className="section-title">Reports — {location.name}</h1>
      <p className="section-sub">Export the current forecast, or review weekly/monthly statistics.</p>

      <div className="flex gap-12 mt">
        <button className="btn" onClick={downloadPdf}>
          Download PDF Report
        </button>
        <button className="btn btn-outline" onClick={downloadCsv}>
          Export CSV
        </button>
      </div>

      <div className="grid grid-2 mt">
        <Card title="Weekly Report (7-day forecast)">
          <div className="grid grid-3">
            <div className="metric-tile">
              <div className="metric-value">{weekHigh.toFixed(0)}°C</div>
              <div className="metric-label">Weekly high</div>
            </div>
            <div className="metric-tile">
              <div className="metric-value">{weekLow.toFixed(0)}°C</div>
              <div className="metric-label">Weekly low</div>
            </div>
            <div className="metric-tile">
              <div className="metric-value">{weekRain.toFixed(0)} mm</div>
              <div className="metric-label">Total rainfall</div>
            </div>
          </div>
        </Card>

        {monthAvg !== null && monthRain !== null && (
          <Card title="Monthly Report (last 30 days)">
            <div className="grid grid-3">
              <div className="metric-tile">
                <div className="metric-value">{monthAvg.toFixed(1)}°C</div>
                <div className="metric-label">Average temp</div>
              </div>
              <div className="metric-tile">
                <div className="metric-value">{monthRain.toFixed(0)} mm</div>
                <div className="metric-label">Total rainfall</div>
              </div>
              <div className="metric-tile">
                <div className="metric-value">
                  {Math.max(...historical.map((d) => d.max)).toFixed(1)}°C
                </div>
                <div className="metric-label">Hottest day</div>
              </div>
            </div>
          </Card>
        )}
      </div>

      <Card title="Weather Statistics — 7-day detail" className="mt">
        <div style={{ overflowX: "auto" }}>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Condition</th>
                <th>High (Day Max)</th>
                <th>Low (Night Min)</th>
                <th>24h Temp Trend</th>
                <th>Rain</th>
                <th>UV Max</th>
                <th>Wind Max</th>
              </tr>
            </thead>
            <tbody>
              {meteo.daily.time.map((date, i) => {
                const high = meteo.daily.temperature_2m_max[i];
                const low = meteo.daily.temperature_2m_min[i];

                const prevHigh =
                  i > 0
                    ? meteo.daily.temperature_2m_max[i - 1]
                    : historical.length > 0
                    ? historical[historical.length - 1]?.max
                    : null;
                const prevLow =
                  i > 0
                    ? meteo.daily.temperature_2m_min[i - 1]
                    : historical.length > 0
                    ? historical[historical.length - 1]?.min
                    : null;

                const deltaHigh =
                  prevHigh !== null && prevHigh !== undefined ? high - prevHigh : null;
                const deltaLow =
                  prevLow !== null && prevLow !== undefined ? low - prevLow : null;

                const dayHourlyTemps = meteo.hourly?.temperature_2m
                  ? meteo.hourly.temperature_2m.slice(i * 24, (i + 1) * 24)
                  : [];

                const code = meteo.daily.weathercode?.[i] ?? 0;
                const codeInfo = getWeatherCodeInfo(code);
                const isToday = i === 0;

                return (
                  <tr key={date}>
                    <td style={{ whiteSpace: "nowrap" }}>
                      <div style={{ fontWeight: 600 }}>
                        {new Date(date).toLocaleDateString("en-US", {
                          weekday: "short",
                          month: "short",
                          day: "numeric",
                        })}
                      </div>
                      {isToday && (
                        <span
                          style={{
                            fontSize: "0.68rem",
                            background: "var(--navy)",
                            color: "white",
                            padding: "1px 6px",
                            borderRadius: "10px",
                            fontWeight: 700,
                            display: "inline-block",
                            marginTop: 2,
                          }}
                        >
                          Today
                        </span>
                      )}
                    </td>
                    <td>
                      <div>
                        <div className="flex items-center gap-8" style={{ whiteSpace: "nowrap" }}>
                          <WeatherIcon code={code} size={24} />
                          <span style={{ fontSize: "0.82rem" }} className="text-muted">
                            {codeInfo.description}
                          </span>
                        </div>
                        <SevereWeatherMarker
                          rain={meteo.daily.precipitation_sum[i]}
                          wind={meteo.daily.windspeed_10m_max[i]}
                          tempMax={high}
                          tempMin={low}
                          weatherCode={code}
                          uvMax={meteo.daily.uv_index_max?.[i]}
                        />
                      </div>
                    </td>
                    <td style={{ whiteSpace: "nowrap" }}>
                      <span style={{ fontWeight: 700, fontSize: "0.95rem" }}>
                        {high.toFixed(0)}°C
                      </span>
                      <TempDelta
                        delta={deltaHigh}
                        label={isToday && historical.length > 0 ? "vs yesterday" : undefined}
                      />
                    </td>
                    <td style={{ whiteSpace: "nowrap" }}>
                      <span
                        style={{
                          fontWeight: 600,
                          fontSize: "0.9rem",
                          color: "var(--text-muted)",
                        }}
                      >
                        {low.toFixed(0)}°C
                      </span>
                      <TempDelta
                        delta={deltaLow}
                        label={isToday && historical.length > 0 ? "vs yesterday" : undefined}
                      />
                    </td>
                    <td>
                      <Sparkline data={dayHourlyTemps} width={120} height={32} />
                    </td>
                    <td style={{ whiteSpace: "nowrap" }}>
                      {meteo.daily.precipitation_sum[i].toFixed(0)} mm
                      {meteo.daily.precipitation_probability_max?.[i] !== undefined && (
                        <span
                          className="text-muted"
                          style={{ fontSize: "0.76rem", marginLeft: 4 }}
                        >
                          ({meteo.daily.precipitation_probability_max[i]}%)
                        </span>
                      )}
                    </td>
                    <td>{meteo.daily.uv_index_max[i].toFixed(1)}</td>
                    <td style={{ whiteSpace: "nowrap" }}>
                      {meteo.daily.windspeed_10m_max[i].toFixed(0)} km/h
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <div
          className="flex items-center gap-12 text-muted"
          style={{
            fontSize: "0.75rem",
            marginTop: 12,
            borderTop: "1px solid var(--card-border)",
            paddingTop: 10,
            flexWrap: "wrap",
          }}
        >
          <span>
            <strong style={{ color: "#ef4444" }}>▲ Warmer</strong> /{" "}
            <strong style={{ color: "#0284c7" }}>▼ Cooler</strong> compared to previous day
          </span>
          <span>•</span>
          <span>Sparklines illustrate 24h temperature diurnal fluctuation (00:00 - 23:00)</span>
        </div>
      </Card>
    </div>
  );
}
